### ISSUE TITLE
ALPS compatible keycaps

### ISSUE THREAD

**Issue by hasufell** [dpapavas/lagrange-keyboard#11]
https://github.com/rsheldiii/KeyV2 is alps and cherry compatible

I'm considering to buy https://matias.ca/switches/linear/ and do another build, but they're ALPS switches.

Would be nice if there's a command line option to switch the keycaps configuration.

EDIT: more context: https://www.reddit.com/r/ErgoMechKeyboards/comments/no8lh2/most_light_smooth_switches/

**Comment by dpapavas** [comment]
>Would be nice if there's a command line option to switch the keycaps configuration.

Keycaps?  As in the stem shape of the printable keycaps?  Alps switches wouldn't mount at all on the current key plate shape, although the changes needed to support them shouldn't be too difficult to implement.

One problem would be that I don't have any switches to test with.  Another would be that I don't intend to do a build myself (well at least for now) and I don't want to publish untested components.  So if you do decide to build another board with ALPS/Matias switches, let me know and I'll try to source a few switches to test with (which, after a cursory search, seems to be tricky in Europe).

**Comment by hasufell** [comment]
I found:

* https://matias.store/products/matias-quiet-linear-switch-box-of-200
* https://www.keyboardco.com/product/matias-quiet-linear-key-switch-module.asp

potentially with import tax, I guess.

But yeah... I'm not sure if I'm going that route. The Gateron clear also look nice and they're cherry compatible.

**Comment by hasufell** [comment]
I bought Gateron clear.
